"""Generate the repository structure map (spec: docs/specs/structure-map.md).

Repository tooling under REQ-001 / ADR-086: standard library only, no project dependency and
no logging framework at all — the entire observable output is the two `--check` lines on
stdout (REQ-005, T-005) and the sorted path lines on stderr (REQ-006). Every source file is
read exactly once: the line count and the AST come from the same read (REQ-001, AC-001).

T-002 owns the harness: the CLI (REQ-002), the file set (REQ-003), the exit-code contract
(REQ-004, codes 2/4/0 here), the unreadable-source hard failure (REQ-006), the document shape
(REQ-008) and the `--out` parent-directory rule (EDGE-006). The Directory tree body is
T-003's, the Packages body is T-004's, and the `--check` comparison is T-005's.
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

# REQ-004 exit codes. 2 is raised by argparse itself (usage errors, EDGE-014); 3 and 1 belong
# to --check (REQ-005) and are inserted by T-005 between the 4 check and the 0 below.
_EXIT_UNREADABLE = 4
_EXIT_OK = 0

# REQ-008 document chrome: this order and nothing else.
_TITLE = "# Repository structure"
_GENERATED_BY = "_Generated by `scripts/make_map.py`. Do not edit by hand._"
_TREE_HEADING = "## Directory tree"
_PACKAGES_HEADING = "## Packages"

# REQ-003 fallback for a non-git --root: the built-in ignore list, and the limitation note
# printed exactly once to stderr (EDGE-007). `.gitignore` is never parsed.
_IGNORED_DIRS = frozenset(
    {".git", ".venv", "__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache", "data", "dist", "build", ".idea"}
)
_IGNORE_NOTE = (
    "note: --root is not a git repository (or git is unavailable): using the built-in ignore "
    "list; .gitignore is not parsed"
)

# REQ-002: --root defaults to the repository root that contains scripts/make_map.py.
_DEFAULT_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Module:
    """One in-scope source file: read once, parsed once (REQ-001)."""

    path: str  # --root-relative POSIX path; the output never holds a host path (REQ-002/REQ-008)
    source: str
    tree: ast.Module
    line_count: int


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    """The six REQ-002 options and nothing else; anything else is an argparse usage error (exit 2)."""
    parser = argparse.ArgumentParser(
        prog="make_map.py",
        description="Generate the repository structure map from the checked-out tree.",
    )
    parser.add_argument(
        "--root",
        default=str(_DEFAULT_ROOT),
        help="the directory the map describes (default: the repository root containing scripts/make_map.py)",
    )
    parser.add_argument(
        "--out",
        default="STRUCTURE.md",
        help="the map file to write or check, resolved against the current working directory (default: STRUCTURE.md)",
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="also render _name functions, methods and classes",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=4,
        help="tree depth counted in path segments from the root, must be >= 1 (default: 4)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the existing map against a fresh render instead of writing it",
    )
    args = parser.parse_args(argv)
    if args.max_depth < 1:  # EDGE-014: usage error, exit 2, no output written
        parser.error("--max-depth must be >= 1")
    return args


def _git_paths(root: Path) -> list[str] | None:
    """`git ls-files --cached --others --exclude-standard` (REQ-003), or None when git cannot answer."""
    try:
        # `-z` keeps names byte-exact: no octal quoting, no path rewriting.
        proc = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
            cwd=root,
            capture_output=True,
            check=False,
        )
    except OSError:  # git is unavailable (EDGE-007)
        return None
    if proc.returncode != 0:  # --root is not a git repository (EDGE-007)
        return None
    return [name for name in proc.stdout.decode("utf-8", "surrogateescape").split("\0") if name]


def _walk_paths(root: Path) -> list[str]:
    """The non-git file set: every `.py` under `root` outside the built-in ignore list (REQ-003)."""
    paths: list[str] = []
    for path in root.rglob("*.py"):
        relative = path.relative_to(root)
        if path.is_file() and _IGNORED_DIRS.isdisjoint(relative.parts[:-1]):  # only directory parts
            paths.append(relative.as_posix())
    return paths


def _file_set(root: Path) -> list[str]:
    """The sorted `.py` files the map describes (REQ-003, AC-003, EDGE-007, EDGE-008).

    Index plus untracked-but-not-ignored, filtered to `.py`, and kept only where the path
    exists on disk — so a new file is mapped before it is `git add`ed and a tracked file
    deleted from the working tree is not mapped at all (EDGE-008, not an error).
    """
    listing = _git_paths(root)
    if listing is None:
        print(_IGNORE_NOTE, file=sys.stderr)  # the limitation note, exactly once (EDGE-007)
        candidates = _walk_paths(root)
    else:
        candidates = [name for name in listing if name.endswith(".py")]
    # Both branches end in the same two rules: `.py`, and present on disk (EDGE-008).
    return sorted(name for name in candidates if (root / name).is_file())


def _read_modules(paths: Sequence[str], root: Path) -> tuple[list[Module], list[str]]:
    """Read and parse every file in the set exactly once (REQ-001, AC-001).

    Returns the modules plus the REQ-006 hard-failure report: one line per unreadable path,
    sorted, `--root`-relative, naming the exception type — and nothing else (no degraded mode,
    no `(parse error)` marker). The report is the whole set, not the first failure.
    """
    modules: list[Module] = []
    failures: list[str] = []
    for path in paths:
        try:
            # The module's only file-content read site (REQ-001 / AC-001): the AST and the line
            # count below both come from this string, so a later renderer must not read again.
            source = (root / path).read_text(encoding="utf-8")
            tree = ast.parse(source, filename=path)
        except (SyntaxError, UnicodeDecodeError, OSError) as error:
            failures.append(f"{path}: {type(error).__name__}")
        else:
            modules.append(Module(path=path, source=source, tree=tree, line_count=len(source.splitlines())))
    return modules, sorted(failures)


def _render(modules: Sequence[Module]) -> str:
    """The REQ-008 document shape: title, one blank line, the generated-by line, then the two
    section headings, in that order and nothing else — no timestamp, no version banner, no
    host path. The section bodies are T-003 (tree) and T-004 (packages)."""
    lines = [_TITLE, "", _GENERATED_BY, "", _TREE_HEADING, ""]
    lines += [f"- {module.path}" for module in modules]
    lines += ["", _PACKAGES_HEADING]
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Run the generator and return its exit code.

    The REQ-004 precedence order 2 -> 4 -> 3 -> 1 -> 0 is the order of this function: argparse
    exits 2 before anything is read, an unreadable source returns 4 before any comparison or
    write, and T-005 inserts the `--check` codes 3 (missing `--out`) then 1 (stale) at the
    marked point, ahead of the 0.
    """
    args = _parse_args(argv)  # 2: argparse raises SystemExit(2) on a usage error
    root = Path(args.root).resolve()
    out = Path(args.out)  # REQ-002: --out resolves against the current working directory

    modules, failures = _read_modules(_file_set(root), root)
    if failures:  # 4: every offending path once, sorted, on stderr; no output file written
        print(*failures, sep="\n", file=sys.stderr)
        return _EXIT_UNREADABLE

    document = _render(modules)
    if args.check:
        # T-005 (REQ-005): compare `document` against the `--out` bytes here and return 3 then 1.
        return _EXIT_OK

    out.parent.mkdir(parents=True, exist_ok=True)  # EDGE-006: create --out's parent when missing
    out.write_text(document, encoding="utf-8", newline="\n")  # generate mode always writes LF
    return _EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
