"""Generate the repository structure map (spec: docs/specs/structure-map.md).

Repository tooling under REQ-001 / ADR-086: standard library only, no project dependency and
no logging framework at all — the entire observable output is the two `--check` lines on
stdout (REQ-005, T-005) and the sorted path lines on stderr (REQ-006). Every source file is
read exactly once: the line count and the AST come from the same read (REQ-001, AC-001).

T-002 owns the harness: the CLI (REQ-002), the file set (REQ-003), the exit-code contract
(REQ-004, the whole table here), the unreadable-source hard failure (REQ-006), the document shape
(REQ-008) and the `--out` parent-directory rule (EDGE-006). T-003 owns the Directory tree body
(REQ-009/REQ-010), the Packages scope, group headers and module sections (REQ-011…REQ-013) and
the path form (REQ-020). T-004 owns the symbol inventory of each module section (REQ-014…REQ-018).
The `--check` comparison and its 3/1 codes are T-005's.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

# REQ-004 exit codes, and nothing else is ever produced. 2 is raised by argparse itself (usage
# errors, EDGE-014); 4 is returned by the REQ-006 report; 3 and 1 belong to --check (REQ-005). The
# order of `main` IS the REQ-004 precedence order 2 -> 4 -> 3 -> 1 -> 0, so an unparseable source
# outranks a missing or stale map (AC-004).
_EXIT_STALE = 1
_EXIT_MISSING = 3
_EXIT_UNREADABLE = 4
_EXIT_OK = 0

# REQ-005: the two --check lines, pinned byte-for-byte (em dash, not hyphen) and naming `--out`
# exactly as it was given. They are the only stdout output of the whole tool (spec §10).
_CHECK_STALE = "{} is out of date \u2014 run uv run python scripts/make_map.py"
_CHECK_MISSING = "{} is missing \u2014 run uv run python scripts/make_map.py"

# REQ-008 document chrome: this order and nothing else.
_TITLE = "# Repository structure"
_GENERATED_BY = "_Generated by `scripts/make_map.py`. Do not edit by hand._"
_TREE_HEADING = "## Directory tree"
_PACKAGES_HEADING = "## Packages"

# REQ-003 fallback for a non-git --root: the built-in ignore list, and the limitation note
# printed exactly once to stderr (EDGE-007). `.gitignore` is never parsed.
_IGNORED_DIRS = frozenset(
    {".git", ".venv", "__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache", "data", "dist", "build", ".idea"}
)
_IGNORE_NOTE = (
    "note: --root is not a git repository (or git is unavailable): using the built-in ignore "
    "list; .gitignore is not parsed"
)

# REQ-002: --root defaults to the repository root that contains scripts/make_map.py.
_DEFAULT_ROOT = Path(__file__).resolve().parents[1]

# REQ-009 clause 2: the top-level directories the tree renders entry by entry (the "code dirs").
_CODE_DIRS: tuple[str, ...] = ("src", "tests", "scripts", "migrations")

# REQ-011: the directories whose every module is in Packages scope.
_PACKAGES_DIRS: tuple[str, ...] = ("src", "scripts", "migrations")

# REQ-012: the import root a package's import name is measured against.
_IMPORT_ROOT = "src/"

# REQ-018: a summary is truncated to this many characters, with the marker appended when longer.
_SUMMARY_LIMIT = 100
_SUMMARY_MARKER = "…"

# REQ-014: a parameter default is rendered only when its ast.unparse text is at most this long.
_DEFAULT_MAX_CHARS = 20

# REQ-014 v2 / EDGE-017: the `…` an over-long default is abbreviated to, in its own slot — the same
# character REQ-018 uses for a long summary. Injected as an `ast.Name` node because `ast.unparse`
# renders a node's `id` verbatim and cannot emit `…` from a real default (a `Constant(...)` renders
# `...`). At 1 character it stays under the threshold, so the rule is idempotent (INV-001).
_DEFAULT_MARKER = "…"

# REQ-017: the number of class fields rendered per class (the NFR-002 safety valve), and the `…`
# marker that reports the elided count — the same character REQ-018 uses for a long summary.
_FIELD_CAP = 15
_FIELD_MARKER = "…"

# REQ-009 clause 3: the fixed built-in role-label table for the count-only top-level directories.
# ponytail: a literal table (spec §13 known-ceiling note). Ceiling: a top-level directory the table
# has no entry for renders an unlabelled count line (EDGE-015), and a new label needs a code change.
# Upgrade path: a config-driven table read at render time.
_ROLE_LABELS: Mapping[str, str] = {
    "docs": "process record",
    ".agents": "skills",
    ".github": "CI and tooling",
    "userdocs": "published docs",
}


@dataclass(frozen=True)
class Module:
    """One in-scope source file: read once, parsed once (REQ-001)."""

    path: str  # --root-relative POSIX path; the output never holds a host path (REQ-002/REQ-008)
    source: str
    tree: ast.Module
    line_count: int


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    """The six REQ-002 options and nothing else; anything else is an argparse usage error (exit 2)."""
    parser = argparse.ArgumentParser(
        prog="make_map.py",
        description="Generate the repository structure map from the checked-out tree.",
    )
    parser.add_argument(
        "--root",
        default=str(_DEFAULT_ROOT),
        help="the directory the map describes (default: the repository root containing scripts/make_map.py)",
    )
    parser.add_argument(
        "--out",
        default="STRUCTURE.md",
        help="the map file to write or check, resolved against the current working directory (default: STRUCTURE.md)",
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="also render _name functions, methods and classes",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=4,
        help="tree depth counted in path segments from the root, must be >= 1 (default: 4)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the existing map against a fresh render instead of writing it",
    )
    args = parser.parse_args(argv)
    if args.max_depth < 1:  # EDGE-014: usage error, exit 2, no output written
        parser.error("--max-depth must be >= 1")
    return args


def _git_paths(root: Path) -> list[str] | None:
    """`git ls-files --cached --others --exclude-standard` (REQ-003), or None when git cannot answer."""
    try:
        # `-z` keeps names byte-exact: no octal quoting, no path rewriting.
        proc = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
            cwd=root,
            capture_output=True,
            check=False,
        )
    except OSError:  # git is unavailable (EDGE-007)
        return None
    if proc.returncode != 0:  # --root is not a git repository (EDGE-007)
        return None
    return [name for name in proc.stdout.decode("utf-8", "surrogateescape").split("\0") if name]


def _walk_paths(root: Path) -> list[str]:
    """The non-git file set: every `.py` under `root` outside the built-in ignore list (REQ-003)."""
    paths: list[str] = []
    for path in root.rglob("*.py"):
        relative = path.relative_to(root)
        if path.is_file() and _IGNORED_DIRS.isdisjoint(relative.parts[:-1]):  # only directory parts
            paths.append(relative.as_posix())
    return paths


def _file_set(root: Path) -> list[str]:
    """The sorted tracked file set the map describes (REQ-003, AC-003, EDGE-007, EDGE-008).

    Index plus untracked-but-not-ignored, kept only where the path exists on disk — so a new file
    is mapped before it is `git add`ed and a tracked file deleted from the working tree is not
    mapped at all (EDGE-008, not an error). Every file type is kept: the tree renders the code dirs
    and counts the other top-level directories over all file types (REQ-009), while the modules are
    the `.py` subset (REQ-003). The non-git fallback can only find `.py` files, so a non-git
    `--root` counts `.py` alone (EDGE-007).
    """
    listing = _git_paths(root)
    if listing is None:
        print(_IGNORE_NOTE, file=sys.stderr)  # the limitation note, exactly once (EDGE-007)
        candidates = _walk_paths(root)
    else:
        candidates = listing
    return sorted(name for name in candidates if (root / name).is_file())


def _read_bytes(path: Path) -> bytes:
    """The generator's one and only file-content read site (REQ-001 / AC-001 clause 3).

    REQ-001 requires each source file to be read exactly once, and the AC-001 witness is a static
    witness of the read *site*, so every file the tool reads — a `.py` source file and, in `--check`
    mode, the existing map — goes through here. Bytes (not text) because the `--check` comparison is
    byte-exact and needs the raw CRLF bytes (REQ-005); the caller decodes.
    """
    return path.read_bytes()


def _read_modules(paths: Sequence[str], root: Path) -> tuple[list[Module], list[str]]:
    """Read and parse every file in the set exactly once (REQ-001, AC-001).

    Returns the modules plus the REQ-006 hard-failure report: one line per unreadable path,
    sorted, `--root`-relative, naming the exception type — and nothing else (no degraded mode,
    no `(parse error)` marker). The report is the whole set, not the first failure.
    """
    modules: list[Module] = []
    failures: list[str] = []
    for path in paths:
        try:
            # The module's only file-content read site (REQ-001 / AC-001): the AST and the line
            # count below both come from this string, so a later renderer must not read again.
            source = _read_bytes(root / path).decode("utf-8")
            tree = ast.parse(source, filename=path)
        except (SyntaxError, UnicodeDecodeError, OSError) as error:
            failures.append(f"{path}: {type(error).__name__}")
        else:
            modules.append(Module(path=path, source=source, tree=tree, line_count=len(source.splitlines())))
    return modules, sorted(failures)


def _children(paths: Sequence[str], prefix: str) -> tuple[list[str], list[str]]:
    """The direct children of the directory `prefix` in the file set: sorted names, then sorted files."""
    dirs: set[str] = set()
    files: list[str] = []
    for path in paths:
        if path.startswith(prefix):
            name, sep, _ = path[len(prefix) :].partition("/")
            if sep:
                dirs.add(name)
            else:
                files.append(name)
    return sorted(dirs), files


def _hidden_counts(paths: Sequence[str], prefix: str) -> tuple[int, int]:
    """REQ-010: how many directories and how many files the `--max-depth` prune hides under `prefix`."""
    below = [path[len(prefix) :] for path in paths if path.startswith(prefix)]
    hidden: set[str] = set()
    for path in below:
        parts = path.split("/")[:-1]
        for index in range(1, len(parts) + 1):
            hidden.add("/".join(parts[:index]))
    return len(hidden), len(below)


def _prune_marker(dirs: int, files: int) -> list[str]:
    """REQ-010's marker line: `(+N dirs not shown)`, `(+N files not shown)`, or the combined form —
    one wording, built from whichever of the two counts is non-zero."""
    parts = [f"{count} {unit}" for count, unit in ((dirs, "dirs"), (files, "files")) if count]
    return [f"(+{', '.join(parts)} not shown)"] if parts else []


def _branch_lines(prefix: str, depth: int, paths: Sequence[str], max_depth: int) -> list[str]:
    """The tree lines of the branch under `prefix` (REQ-009 clause 2), one per directory and per
    entry, sorted, indented two spaces per level. `--max-depth` prunes this branch only (REQ-010):
    the deepest rendered directory carries the marker for everything below the limit."""
    indent = "  " * depth
    if depth >= max_depth:
        hidden_dirs, hidden_files = _hidden_counts(paths, prefix)
        return [f"{indent}{line}" for line in _prune_marker(hidden_dirs, hidden_files)]
    lines: list[str] = []
    dirs, files = _children(paths, prefix)
    for name in dirs:
        child = f"{prefix}{name}/"
        lines.append(f"{indent}{child}")
        lines += _branch_lines(child, depth + 1, paths, max_depth)
    return lines + [f"{indent}{prefix}{name}" for name in files]


def _top_level_counts(paths: Sequence[str]) -> dict[str, int]:
    """How many files sit under each top-level directory of the file set — the one place the
    top-level split is derived; the code dirs are rendered in full, the rest are counted."""
    counts: dict[str, int] = {}
    for path in paths:
        name, sep, _ = path.partition("/")
        if sep:
            counts[name] = counts.get(name, 0) + 1
    return counts


def _count_lines(counts: Mapping[str, int]) -> list[str]:
    """REQ-009 clause 3: one count line per top-level directory that is not a code dir, with its
    role label when the built-in table has one and no label when it does not (EDGE-015)."""
    return [
        f"{name}/ \u2014 {count} files" + (f" ({label})" if (label := _ROLE_LABELS.get(name)) else "")
        for name, count in sorted(counts.items())
        if name not in _CODE_DIRS
    ]


def _tree_lines(paths: Sequence[str], max_depth: int) -> list[str]:
    """The Directory tree block in REQ-009 order: the top-level files by name, then every code dir
    rendered in full within `--max-depth`, then one count line per other top-level directory."""
    counts = _top_level_counts(paths)
    lines: list[str] = [path for path in paths if "/" not in path]
    for name in _CODE_DIRS:
        if name in counts:
            lines.append(f"{name}/")
            lines += _branch_lines(f"{name}/", 1, paths, max_depth)
    return lines + _count_lines(counts)


def _in_packages_scope(path: str) -> bool:
    """REQ-011: every module under a packages dir, plus each `tests/` `conftest.py` or
    `*_test_helpers.py`. No other `tests/` module, and never a `.py` outside a code dir (REQ-010)."""
    top = path.split("/", 1)[0]
    name = path.rsplit("/", 1)[-1]
    return top in _PACKAGES_DIRS or (top == "tests" and (name == "conftest.py" or name.endswith("_test_helpers.py")))


def _summary(docstring: str | None) -> str:
    """REQ-018: the normalized first logical line of a docstring; "" when there is none (an empty
    docstring counts as none, EDGE-001)."""
    if not docstring:
        return ""
    paragraph: list[str] = []
    for line in inspect.cleandoc(docstring).splitlines():
        if not line.strip():
            break
        paragraph.append(line)
    text = " ".join(" ".join(paragraph).replace("`", "").split())
    return f"{text[:_SUMMARY_LIMIT]}{_SUMMARY_MARKER}" if len(text) > _SUMMARY_LIMIT else text


def _all_assignment(node: ast.stmt) -> ast.expr | None:
    """The value `node` assigns to `__all__`, None when it assigns no `__all__` (REQ-012)."""
    if isinstance(node, ast.Assign):
        targets, value = node.targets, node.value
    elif isinstance(node, ast.AnnAssign) and node.value is not None:
        targets, value = [node.target], node.value
    else:
        return None
    if not any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
        return None
    return value


def _dunder_all(tree: ast.Module) -> list[str]:
    """The names of a module's `__all__` assignment, [] when it defines none or binds anything but a
    literal sequence (REQ-012)."""
    for node in tree.body:
        value = _all_assignment(node)
        if value is None:
            continue
        if isinstance(value, ast.List | ast.Tuple | ast.Set):
            return [str(item.value) for item in value.elts if isinstance(item, ast.Constant)]
        return []
    return []


def _imported_names(node: ast.stmt) -> list[str]:
    """The names a module-level import statement binds (REQ-012's exports fallback)."""
    if isinstance(node, ast.Import):
        return [alias.asname or alias.name.split(".")[0] for alias in node.names]
    if isinstance(node, ast.ImportFrom):
        return [alias.asname or alias.name for alias in node.names if alias.name != "*"]
    return []


def _public_imports(tree: ast.Module) -> list[str]:
    """The public names a module imports at module level — REQ-012's exports fallback."""
    names = [name for node in tree.body for name in _imported_names(node)]
    return [name for name in names if not name.startswith("_")]


def _group_header(directory: str, init: Module | None) -> str:
    """REQ-012: one header per containing directory — the import name and the `--root`-relative path
    for a package (an `__init__.py`), the path alone for a plain directory; never one per module."""
    path = f"{directory}/"
    if init is None:
        return f"### {path}"
    relative = directory.removeprefix(_IMPORT_ROOT)
    return f"### `{relative.replace('/', '.')}` \u2014 {path}"


def _abbreviate_default(default: ast.expr) -> ast.expr:
    """REQ-014 v2: `default` when its unparsed text fits the threshold, the `…` placeholder when it
    does not — a substitution, never a deletion."""
    return default if len(ast.unparse(default)) <= _DEFAULT_MAX_CHARS else ast.Name(id=_DEFAULT_MARKER)


def _drop_long_defaults(args: ast.arguments) -> None:
    """REQ-014/EDGE-017: abbreviate a parameter default to `…` when its unparsed text is > 20 characters.

    Mutates the parsed tree (each module is rendered once, and the substitution is idempotent).
    The abbreviation happens **in the default's own slot**: deleting a positional default instead
    shifts the kept ones onto earlier parameters and deleting a keyword-only one renders that
    parameter as required, so the map misrepresents the source signature — a reader concludes a
    parameter is mandatory, or reads a default that belongs to another parameter (INV-007).

    `kw_defaults` is aligned one-to-one with `kwonlyargs` and holds None for a keyword-only
    parameter that has **no** default: None stays None, so a required parameter never gains `=…`."""
    args.defaults = [_abbreviate_default(d) for d in args.defaults]
    args.kw_defaults = [None if d is None else _abbreviate_default(d) for d in args.kw_defaults]


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """REQ-014: the backticked signature of a function or method — parameters, annotations and
    return annotation rendered by `ast.unparse`, so source formatting drift cannot change the map.
    The `def ` keyword is dropped (a method line carries none); an `async def` keeps its `async `
    prefix inside the backticks.

    The parts are unparsed separately rather than the whole node: `ast.unparse` of a function
    definition also renders the decorators REQ-015 renders as its own prefix, and the body."""
    _drop_long_defaults(node.args)
    generics = f"[{', '.join(ast.unparse(param) for param in node.type_params)}]" if node.type_params else ""
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    return f"{prefix}{node.name}{generics}({ast.unparse(node.args)}){returns}"


def _class_name(node: ast.ClassDef) -> str:
    """REQ-014: the class line's backticked `Name(Base, ...)` — bases and class keywords unparsed."""
    parts = [ast.unparse(base) for base in node.bases]
    parts += [f"{kw.arg}={ast.unparse(kw.value)}" for kw in node.keywords if kw.arg]
    return f"{node.name}({', '.join(parts)})" if parts else node.name


def _field_lines(body: Sequence[ast.stmt], indent: str) -> list[str]:
    """REQ-017: the class-level annotated assignments of `body` as `name: annotation` lines — no
    default value and no `Field(...)` payload — in source order, capped at 15 per class, followed by
    the `… +N fields` marker when a class has more (EDGE-011). An unannotated class-level
    assignment is not a field: it renders nothing and is not counted by the cap."""
    lines = [
        f"{indent}- `{ast.unparse(node.target)}: {ast.unparse(node.annotation)}`"
        for node in body
        if isinstance(node, ast.AnnAssign) and node.annotation is not None
    ]
    if len(lines) > _FIELD_CAP:
        elided = len(lines) - _FIELD_CAP
        return [*lines[:_FIELD_CAP], f"{indent}- {_FIELD_MARKER} +{elided} fields"]
    return lines


def _public(name: str) -> bool:
    """REQ-016 (Definitions: public symbol): a dunder name is public; a `_name` is not."""
    return not name.startswith("_") or name.endswith("__")


def _visible(node: ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef, include_private: bool) -> bool:
    """REQ-016: a public symbol always renders; a `_name` function, method or class renders only when
    `--include-private` was passed."""
    return include_private or _public(node.name)


def _symbol_line(node: ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef, indent: str, keyword: str) -> str:
    """One REQ-014 symbol line: indent, bullet, every decorator as a compact `@name` prefix in
    source order (REQ-015 — `ast.unparse` renders a call or subscript decorator as its text), the
    keyword (`class ` for a class, `def ` for a module-level function, nothing for a method), the
    backticked name or signature, and `: ` + summary only when the symbol has one (REQ-018)."""
    decorators = "".join(f"@{ast.unparse(decorator)} " for decorator in node.decorator_list)
    target = _class_name(node) if isinstance(node, ast.ClassDef) else _signature(node)
    head = f"{indent}- {decorators}{keyword}`{target}`"
    return f"{head}: {summary}" if (summary := _summary(ast.get_docstring(node))) else head


def _member_lines(body: Sequence[ast.stmt], indent: str, include_private: bool) -> list[str]:
    """The REQ-014 symbol lines of one module body or one class body, grouped and each group in
    source order: the classes first — each class line, then its REQ-017 fields, then its own members
    one indent deeper — then the functions. The `indent` says which level this is: a module-level
    function carries the `def ` keyword and no indent, a method carries neither (REQ-014), and
    REQ-016 decides which symbols render. Statements that are not symbols (assignments, imports,
    `if TYPE_CHECKING` blocks) render nothing, and only module- and class-level statements are
    walked, so a class or function defined inside a function body is never reached."""
    inner = indent + "  "
    lines: list[str] = []
    for node in body:
        if isinstance(node, ast.ClassDef) and _visible(node, include_private):
            lines.append(_symbol_line(node, indent, "class "))
            lines += _field_lines(node.body, inner)
            lines += _member_lines(node.body, inner, include_private)
    for node in body:
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and _visible(node, include_private):
            lines.append(_symbol_line(node, indent, "def " if not indent else ""))
    return lines


def _module_lines(module: Module, include_private: bool) -> list[str]:
    """REQ-013: the module header with its line count, then its summary line only when the module has
    a docstring (EDGE-001 module half, EDGE-002: an empty file renders its header alone, no error),
    then its REQ-014 symbol inventory."""
    lines = [f"#### {module.path} ({module.line_count} lines)"]
    if summary := _summary(ast.get_docstring(module.tree)):
        lines.append(summary)
    return lines + _member_lines(module.tree.body, "", include_private)


def _packages_lines(modules: Sequence[Module], include_private: bool) -> list[str]:
    """The Packages section: the REQ-011 scope in path order, grouped by containing directory
    (REQ-012) — one header per directory, the exports line when the package has one (EDGE-013: no
    line when it has neither `__all__` nor public imports), then each module section (REQ-013) with
    its symbol inventory (REQ-014…REQ-018). `--include-private` changes only which symbols render
    here, never which modules or packages appear (REQ-016). No in-scope module is ever elided for
    size, whatever `--max-depth` pruned in the tree (INV-002)."""
    parsed = {module.path: module for module in modules}
    groups: dict[str, list[Module]] = {}
    for module in sorted((m for m in modules if _in_packages_scope(m.path)), key=lambda m: m.path):
        groups.setdefault(module.path.rsplit("/", 1)[0], []).append(module)
    lines: list[str] = []
    for directory, group in groups.items():
        init = parsed.get(f"{directory}/__init__.py")
        lines.append(_group_header(directory, init))
        if init is not None and (names := _dunder_all(init.tree) or _public_imports(init.tree)):
            lines.append(f"exports: {', '.join(sorted(names))}")
        for module in group:
            lines += _module_lines(module, include_private)
        lines.append("")
    return lines


def _render(modules: Sequence[Module], paths: Sequence[str], max_depth: int, include_private: bool) -> str:
    """The REQ-008 document shape: title, one blank line, the generated-by line, then the two
    section headings, in that order and nothing else — no timestamp, no version banner, no
    host path (REQ-020: every path here is `--root`-relative POSIX). The tree body is REQ-009 and
    REQ-010, the Packages body REQ-011…REQ-013; REQ-019's LF newlines and single final newline."""
    lines = [_TITLE, "", _GENERATED_BY, "", _TREE_HEADING, ""]
    lines += _tree_lines(paths, max_depth)
    lines += ["", _PACKAGES_HEADING, ""]
    lines += _packages_lines(modules, include_private)
    return "\n".join(lines).rstrip("\n") + "\n"


def _print_line(message: str) -> None:
    """One line on stdout, always UTF-8 (NFR-007): the pinned REQ-005 messages carry an em dash, and
    the default codec of a redirected Windows stdout is cp1252, which cannot encode it."""
    if hasattr(sys.stdout, "reconfigure"):  # the same guard as scripts/verify_spec.py
        sys.stdout.reconfigure(encoding="utf-8")
    print(message)


def _check(out: Path, out_arg: str, document: str) -> int:
    """REQ-005 / INV-004: compare the whole `--out` file against `document` byte-for-byte, after the
    single CRLF -> LF normalisation and nothing else (no whitespace-insensitive diffing, no
    section-level comparison) — so a CRLF checkout of the committed LF blob is not stale (EDGE-016)
    while a one-byte or whitespace-only difference is (EDGE-010). Exactly one pinned line on stdout,
    nothing on stderr, and nothing is written (INV-005): `--out` is only ever read here.

    `out_arg` is the `--out` value as given, which is what the message must name (AC-005)."""
    if not out.is_file():  # 3: reported, never created
        _print_line(_CHECK_MISSING.format(out_arg))
        return _EXIT_MISSING
    if _read_bytes(out).replace(b"\r\n", b"\n") != document.encode("utf-8"):
        _print_line(_CHECK_STALE.format(out_arg))
        return _EXIT_STALE
    return _EXIT_OK


def main(argv: Sequence[str] | None = None) -> int:
    """Run the generator and return its exit code.

    The REQ-004 precedence order 2 -> 4 -> 3 -> 1 -> 0 is the order of this function: argparse
    exits 2 before anything is read, an unreadable source returns 4 before any comparison or
    write, `--check` then returns 3 (missing `--out`) or 1 (stale) ahead of the 0, and 1/3 are
    unreachable in generate mode because that mode never reaches `_check`.
    """
    args = _parse_args(argv)  # 2: argparse raises SystemExit(2) on a usage error
    root = Path(args.root).resolve()
    out = Path(args.out)  # REQ-002: --out resolves against the current working directory

    paths = _file_set(root)
    modules, failures = _read_modules([path for path in paths if path.endswith(".py")], root)
    if failures:  # 4: every offending path once, sorted, on stderr; no output file written
        print(*failures, sep="\n", file=sys.stderr)
        return _EXIT_UNREADABLE

    document = _render(modules, paths, args.max_depth, args.include_private)
    if args.check:  # 3 then 1: the render is only compared, never written (INV-005)
        return _check(out, args.out, document)

    out.parent.mkdir(parents=True, exist_ok=True)  # EDGE-006: create --out's parent when missing
    out.write_text(document, encoding="utf-8", newline="\n")  # generate mode always writes LF
    return _EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
