"""Generate the repository structure map (spec: docs/specs/structure-map.md).

Repository tooling under REQ-001 / ADR-086: standard library only, no project dependency and
no logging framework at all — the entire observable output is the two `--check` lines on
stdout (REQ-005, T-005) and the sorted path lines on stderr (REQ-006). Every source file is
read exactly once: the line count and the AST come from the same read (REQ-001, AC-001).

T-002 owns the harness: the CLI (REQ-002), the file set (REQ-003), the exit-code contract
(REQ-004, codes 2/4/0 here), the unreadable-source hard failure (REQ-006), the document shape
(REQ-008) and the `--out` parent-directory rule (EDGE-006). T-003 owns the Directory tree body
(REQ-009/REQ-010), the Packages scope, group headers and module sections (REQ-011…REQ-013) and
the path form (REQ-020). The symbol bodies of each module section are T-004's, and the `--check`
comparison is T-005's.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

# REQ-004 exit codes. 2 is raised by argparse itself (usage errors, EDGE-014); 3 and 1 belong
# to --check (REQ-005) and are inserted by T-005 between the 4 check and the 0 below.
_EXIT_UNREADABLE = 4
_EXIT_OK = 0

# REQ-008 document chrome: this order and nothing else.
_TITLE = "# Repository structure"
_GENERATED_BY = "_Generated by `scripts/make_map.py`. Do not edit by hand._"
_TREE_HEADING = "## Directory tree"
_PACKAGES_HEADING = "## Packages"

# REQ-003 fallback for a non-git --root: the built-in ignore list, and the limitation note
# printed exactly once to stderr (EDGE-007). `.gitignore` is never parsed.
_IGNORED_DIRS = frozenset(
    {".git", ".venv", "__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache", "data", "dist", "build", ".idea"}
)
_IGNORE_NOTE = (
    "note: --root is not a git repository (or git is unavailable): using the built-in ignore "
    "list; .gitignore is not parsed"
)

# REQ-002: --root defaults to the repository root that contains scripts/make_map.py.
_DEFAULT_ROOT = Path(__file__).resolve().parents[1]

# REQ-009 clause 2: the top-level directories the tree renders entry by entry (the "code dirs").
_CODE_DIRS: tuple[str, ...] = ("src", "tests", "scripts", "migrations")

# REQ-011: the directories whose every module is in Packages scope.
_PACKAGES_DIRS: tuple[str, ...] = ("src", "scripts", "migrations")

# REQ-012: the import root a package's import name is measured against.
_IMPORT_ROOT = "src/"

# REQ-018: a summary is truncated to this many characters, with the marker appended when longer.
_SUMMARY_LIMIT = 100
_SUMMARY_MARKER = "…"

# REQ-009 clause 3: the fixed built-in role-label table for the count-only top-level directories.
# ponytail: a literal table (spec §13 known-ceiling note). Ceiling: a top-level directory the table
# has no entry for renders an unlabelled count line (EDGE-015), and a new label needs a code change.
# Upgrade path: a config-driven table read at render time.
_ROLE_LABELS: Mapping[str, str] = {
    "docs": "process record",
    ".agents": "skills",
    ".github": "CI and tooling",
    "userdocs": "published docs",
}


@dataclass(frozen=True)
class Module:
    """One in-scope source file: read once, parsed once (REQ-001)."""

    path: str  # --root-relative POSIX path; the output never holds a host path (REQ-002/REQ-008)
    source: str
    tree: ast.Module
    line_count: int


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    """The six REQ-002 options and nothing else; anything else is an argparse usage error (exit 2)."""
    parser = argparse.ArgumentParser(
        prog="make_map.py",
        description="Generate the repository structure map from the checked-out tree.",
    )
    parser.add_argument(
        "--root",
        default=str(_DEFAULT_ROOT),
        help="the directory the map describes (default: the repository root containing scripts/make_map.py)",
    )
    parser.add_argument(
        "--out",
        default="STRUCTURE.md",
        help="the map file to write or check, resolved against the current working directory (default: STRUCTURE.md)",
    )
    parser.add_argument(
        "--include-private",
        action="store_true",
        help="also render _name functions, methods and classes",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=4,
        help="tree depth counted in path segments from the root, must be >= 1 (default: 4)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the existing map against a fresh render instead of writing it",
    )
    args = parser.parse_args(argv)
    if args.max_depth < 1:  # EDGE-014: usage error, exit 2, no output written
        parser.error("--max-depth must be >= 1")
    return args


def _git_paths(root: Path) -> list[str] | None:
    """`git ls-files --cached --others --exclude-standard` (REQ-003), or None when git cannot answer."""
    try:
        # `-z` keeps names byte-exact: no octal quoting, no path rewriting.
        proc = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
            cwd=root,
            capture_output=True,
            check=False,
        )
    except OSError:  # git is unavailable (EDGE-007)
        return None
    if proc.returncode != 0:  # --root is not a git repository (EDGE-007)
        return None
    return [name for name in proc.stdout.decode("utf-8", "surrogateescape").split("\0") if name]


def _walk_paths(root: Path) -> list[str]:
    """The non-git file set: every `.py` under `root` outside the built-in ignore list (REQ-003)."""
    paths: list[str] = []
    for path in root.rglob("*.py"):
        relative = path.relative_to(root)
        if path.is_file() and _IGNORED_DIRS.isdisjoint(relative.parts[:-1]):  # only directory parts
            paths.append(relative.as_posix())
    return paths


def _file_set(root: Path) -> list[str]:
    """The sorted tracked file set the map describes (REQ-003, AC-003, EDGE-007, EDGE-008).

    Index plus untracked-but-not-ignored, kept only where the path exists on disk — so a new file
    is mapped before it is `git add`ed and a tracked file deleted from the working tree is not
    mapped at all (EDGE-008, not an error). Every file type is kept: the tree renders the code dirs
    and counts the other top-level directories over all file types (REQ-009), while the modules are
    the `.py` subset (REQ-003). The non-git fallback can only find `.py` files, so a non-git
    `--root` counts `.py` alone (EDGE-007).
    """
    listing = _git_paths(root)
    if listing is None:
        print(_IGNORE_NOTE, file=sys.stderr)  # the limitation note, exactly once (EDGE-007)
        candidates = _walk_paths(root)
    else:
        candidates = listing
    return sorted(name for name in candidates if (root / name).is_file())


def _read_modules(paths: Sequence[str], root: Path) -> tuple[list[Module], list[str]]:
    """Read and parse every file in the set exactly once (REQ-001, AC-001).

    Returns the modules plus the REQ-006 hard-failure report: one line per unreadable path,
    sorted, `--root`-relative, naming the exception type — and nothing else (no degraded mode,
    no `(parse error)` marker). The report is the whole set, not the first failure.
    """
    modules: list[Module] = []
    failures: list[str] = []
    for path in paths:
        try:
            # The module's only file-content read site (REQ-001 / AC-001): the AST and the line
            # count below both come from this string, so a later renderer must not read again.
            source = (root / path).read_text(encoding="utf-8")
            tree = ast.parse(source, filename=path)
        except (SyntaxError, UnicodeDecodeError, OSError) as error:
            failures.append(f"{path}: {type(error).__name__}")
        else:
            modules.append(Module(path=path, source=source, tree=tree, line_count=len(source.splitlines())))
    return modules, sorted(failures)


def _children(paths: Sequence[str], prefix: str) -> tuple[list[str], list[str]]:
    """The direct children of the directory `prefix` in the file set: sorted names, then sorted files."""
    dirs: set[str] = set()
    files: list[str] = []
    for path in paths:
        if path.startswith(prefix):
            name, sep, _ = path[len(prefix) :].partition("/")
            if sep:
                dirs.add(name)
            else:
                files.append(name)
    return sorted(dirs), files


def _hidden_counts(paths: Sequence[str], prefix: str) -> tuple[int, int]:
    """REQ-010: how many directories and how many files the `--max-depth` prune hides under `prefix`."""
    below = [path[len(prefix) :] for path in paths if path.startswith(prefix)]
    hidden: set[str] = set()
    for path in below:
        parts = path.split("/")[:-1]
        for index in range(1, len(parts) + 1):
            hidden.add("/".join(parts[:index]))
    return len(hidden), len(below)


def _prune_marker(dirs: int, files: int) -> list[str]:
    """REQ-010's marker line: `(+N dirs not shown)`, `(+N files not shown)`, or the combined form —
    one wording, built from whichever of the two counts is non-zero."""
    parts = [f"{count} {unit}" for count, unit in ((dirs, "dirs"), (files, "files")) if count]
    return [f"(+{', '.join(parts)} not shown)"] if parts else []


def _branch_lines(prefix: str, depth: int, paths: Sequence[str], max_depth: int) -> list[str]:
    """The tree lines of the branch under `prefix` (REQ-009 clause 2), one per directory and per
    entry, sorted, indented two spaces per level. `--max-depth` prunes this branch only (REQ-010):
    the deepest rendered directory carries the marker for everything below the limit."""
    indent = "  " * depth
    if depth >= max_depth:
        hidden_dirs, hidden_files = _hidden_counts(paths, prefix)
        return [f"{indent}{line}" for line in _prune_marker(hidden_dirs, hidden_files)]
    lines: list[str] = []
    dirs, files = _children(paths, prefix)
    for name in dirs:
        child = f"{prefix}{name}/"
        lines.append(f"{indent}{child}")
        lines += _branch_lines(child, depth + 1, paths, max_depth)
    return lines + [f"{indent}{prefix}{name}" for name in files]


def _top_level_counts(paths: Sequence[str]) -> dict[str, int]:
    """How many files sit under each top-level directory of the file set — the one place the
    top-level split is derived; the code dirs are rendered in full, the rest are counted."""
    counts: dict[str, int] = {}
    for path in paths:
        name, sep, _ = path.partition("/")
        if sep:
            counts[name] = counts.get(name, 0) + 1
    return counts


def _count_lines(counts: Mapping[str, int]) -> list[str]:
    """REQ-009 clause 3: one count line per top-level directory that is not a code dir, with its
    role label when the built-in table has one and no label when it does not (EDGE-015)."""
    return [
        f"{name}/ \u2014 {count} files" + (f" ({label})" if (label := _ROLE_LABELS.get(name)) else "")
        for name, count in sorted(counts.items())
        if name not in _CODE_DIRS
    ]


def _tree_lines(paths: Sequence[str], max_depth: int) -> list[str]:
    """The Directory tree block in REQ-009 order: the top-level files by name, then every code dir
    rendered in full within `--max-depth`, then one count line per other top-level directory."""
    counts = _top_level_counts(paths)
    lines: list[str] = [path for path in paths if "/" not in path]
    for name in _CODE_DIRS:
        if name in counts:
            lines.append(f"{name}/")
            lines += _branch_lines(f"{name}/", 1, paths, max_depth)
    return lines + _count_lines(counts)


def _in_packages_scope(path: str) -> bool:
    """REQ-011: every module under a packages dir, plus each `tests/` `conftest.py` or
    `*_test_helpers.py`. No other `tests/` module, and never a `.py` outside a code dir (REQ-010)."""
    top = path.split("/", 1)[0]
    name = path.rsplit("/", 1)[-1]
    return top in _PACKAGES_DIRS or (top == "tests" and (name == "conftest.py" or name.endswith("_test_helpers.py")))


def _summary(docstring: str | None) -> str:
    """REQ-018: the normalized first logical line of a docstring; "" when there is none (an empty
    docstring counts as none, EDGE-001)."""
    if not docstring:
        return ""
    paragraph: list[str] = []
    for line in inspect.cleandoc(docstring).splitlines():
        if not line.strip():
            break
        paragraph.append(line)
    text = " ".join(" ".join(paragraph).replace("`", "").split())
    return f"{text[:_SUMMARY_LIMIT]}{_SUMMARY_MARKER}" if len(text) > _SUMMARY_LIMIT else text


def _all_assignment(node: ast.stmt) -> ast.expr | None:
    """The value `node` assigns to `__all__`, None when it assigns no `__all__` (REQ-012)."""
    if isinstance(node, ast.Assign):
        targets, value = node.targets, node.value
    elif isinstance(node, ast.AnnAssign) and node.value is not None:
        targets, value = [node.target], node.value
    else:
        return None
    if not any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
        return None
    return value


def _dunder_all(tree: ast.Module) -> list[str]:
    """The names of a module's `__all__` assignment, [] when it defines none or binds anything but a
    literal sequence (REQ-012)."""
    for node in tree.body:
        value = _all_assignment(node)
        if value is None:
            continue
        if isinstance(value, ast.List | ast.Tuple | ast.Set):
            return [str(item.value) for item in value.elts if isinstance(item, ast.Constant)]
        return []
    return []


def _imported_names(node: ast.stmt) -> list[str]:
    """The names a module-level import statement binds (REQ-012's exports fallback)."""
    if isinstance(node, ast.Import):
        return [alias.asname or alias.name.split(".")[0] for alias in node.names]
    if isinstance(node, ast.ImportFrom):
        return [alias.asname or alias.name for alias in node.names if alias.name != "*"]
    return []


def _public_imports(tree: ast.Module) -> list[str]:
    """The public names a module imports at module level — REQ-012's exports fallback."""
    names = [name for node in tree.body for name in _imported_names(node)]
    return [name for name in names if not name.startswith("_")]


def _group_header(directory: str, init: Module | None) -> str:
    """REQ-012: one header per containing directory — the import name and the `--root`-relative path
    for a package (an `__init__.py`), the path alone for a plain directory; never one per module."""
    path = f"{directory}/"
    if init is None:
        return f"### {path}"
    relative = directory.removeprefix(_IMPORT_ROOT)
    return f"### `{relative.replace('/', '.')}` \u2014 {path}"


def _module_lines(module: Module) -> list[str]:
    """REQ-013: the module header with its line count, then its summary line only when the module has
    a docstring (EDGE-001 module half, EDGE-002: an empty file renders its header alone, no error)."""
    lines = [f"#### {module.path} ({module.line_count} lines)"]
    if summary := _summary(ast.get_docstring(module.tree)):
        lines.append(summary)
    return lines


def _packages_lines(modules: Sequence[Module]) -> list[str]:
    """The Packages section: the REQ-011 scope in path order, grouped by containing directory
    (REQ-012) — one header per directory, the exports line when the package has one (EDGE-013: no
    line when it has neither `__all__` nor public imports), then each module section (REQ-013). The
    symbol bodies are T-004's. No in-scope module is ever elided for size, whatever `--max-depth`
    pruned in the tree (INV-002)."""
    parsed = {module.path: module for module in modules}
    groups: dict[str, list[Module]] = {}
    for module in sorted((m for m in modules if _in_packages_scope(m.path)), key=lambda m: m.path):
        groups.setdefault(module.path.rsplit("/", 1)[0], []).append(module)
    lines: list[str] = []
    for directory, group in groups.items():
        init = parsed.get(f"{directory}/__init__.py")
        lines.append(_group_header(directory, init))
        if init is not None and (names := _dunder_all(init.tree) or _public_imports(init.tree)):
            lines.append(f"exports: {', '.join(sorted(names))}")
        for module in group:
            lines += _module_lines(module)
        lines.append("")
    return lines


def _render(modules: Sequence[Module], paths: Sequence[str], max_depth: int) -> str:
    """The REQ-008 document shape: title, one blank line, the generated-by line, then the two
    section headings, in that order and nothing else — no timestamp, no version banner, no
    host path (REQ-020: every path here is `--root`-relative POSIX). The tree body is REQ-009 and
    REQ-010, the Packages body REQ-011…REQ-013; REQ-019's LF newlines and single final newline."""
    lines = [_TITLE, "", _GENERATED_BY, "", _TREE_HEADING, ""]
    lines += _tree_lines(paths, max_depth)
    lines += ["", _PACKAGES_HEADING, ""]
    lines += _packages_lines(modules)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Run the generator and return its exit code.

    The REQ-004 precedence order 2 -> 4 -> 3 -> 1 -> 0 is the order of this function: argparse
    exits 2 before anything is read, an unreadable source returns 4 before any comparison or
    write, and T-005 inserts the `--check` codes 3 (missing `--out`) then 1 (stale) at the
    marked point, ahead of the 0.
    """
    args = _parse_args(argv)  # 2: argparse raises SystemExit(2) on a usage error
    root = Path(args.root).resolve()
    out = Path(args.out)  # REQ-002: --out resolves against the current working directory

    paths = _file_set(root)
    modules, failures = _read_modules([path for path in paths if path.endswith(".py")], root)
    if failures:  # 4: every offending path once, sorted, on stderr; no output file written
        print(*failures, sep="\n", file=sys.stderr)
        return _EXIT_UNREADABLE

    document = _render(modules, paths, args.max_depth)
    if args.check:
        # T-005 (REQ-005): compare `document` against the `--out` bytes here and return 3 then 1.
        return _EXIT_OK

    out.parent.mkdir(parents=True, exist_ok=True)  # EDGE-006: create --out's parent when missing
    out.write_text(document, encoding="utf-8", newline="\n")  # generate mode always writes LF
    return _EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
